//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Produktseite.Account {
    
    
    public partial class AddPhoneNumber {
        
        /// <summary>
        /// ErrorMessage-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ErrorMessage;
        
        /// <summary>
        /// PhoneNumber-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox PhoneNumber;
    }
}
