//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code wird erneut generiert. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Produktseite.Account {
    
    
    public partial class Manage {
        
        /// <summary>
        /// successMessage-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successMessage;
        
        /// <summary>
        /// ChangePassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ChangePassword;
        
        /// <summary>
        /// CreatePassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink CreatePassword;
        
        /// <summary>
        /// PhoneNumber-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PhoneNumber;
    }
}
