//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code wird erneut generiert. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Produktseite.Account {
    
    
    public partial class OpenAuthProviders {
        
        /// <summary>
        /// providerDetails-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView providerDetails;
    }
}
